import { formatDisplayDateTime } from "../dates/format";
import { buildCrossCheckFingerprint, shortFingerprint } from "./integrityFingerprints";
import type { VerificationReport } from "./verificationReport";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function renderIssueList(items: string[]): string {
  if (items.length === 0) {
    return "<p class=\"muted\">No issues detected.</p>";
  }

  const listItems = items.map((item) => `<li>${escapeHtml(item)}</li>`).join("");
  return `<ul>${listItems}</ul>`;
}

function renderPolicySection(report: VerificationReport): string {
  const policy = report.manifest.redactionPolicy;

  if (!policy) {
    return `
      <section class="card" style="margin-top: 20px;">
        <h2>Redaction Policy</h2>
        <p class="muted">No policy metadata was embedded in this verification report.</p>
      </section>`;
  }

  const omittedList =
    policy.translation.omittedFieldLabels.length > 0
      ? renderIssueList(policy.translation.omittedFieldLabels)
      : "<p class=\"muted\">No fields were omitted by policy.</p>";

  return `
      <section class="card" style="margin-top: 20px;">
        <h2>Redaction Policy</h2>
        <p><strong>Policy:</strong> ${escapeHtml(policy.translation.heading)}</p>
        <p>${escapeHtml(policy.translation.summary)}</p>
        <p>${escapeHtml(policy.translation.attachmentHandling)}</p>
        <p>${escapeHtml(policy.translation.metadataAppendixHandling)}</p>
        <p><strong>Omitted by policy:</strong></p>
        ${omittedList}
      </section>`;
}

function renderSecurityFingerprintSection(report: VerificationReport): string {
  return `
      <section class="card" style="margin-top: 20px; border-color: #8a5a00; background: #fff7e6;">
        <h2>Security Fingerprint</h2>
        <p>Use this compact reference to compare the certificate against the JSON verification report and on-screen verifier.</p>
        <p class="mono"><strong>Cross-check:</strong> ${escapeHtml(
          buildCrossCheckFingerprint(report.manifest.integritySeal, report.reportSha256)
        )}</p>
        <p class="mono"><strong>Manifest seal:</strong> ${escapeHtml(shortFingerprint(report.manifest.integritySeal, 4, 5))}</p>
        <p class="mono"><strong>Report checksum:</strong> ${escapeHtml(shortFingerprint(report.reportSha256, 4, 5))}</p>
      </section>`;
}

export function generateClinicalVerificationCertificateHtml(report: VerificationReport): string {
  const passed = report.status === "verified";
  const title = report.manifest.caseTitle ?? report.manifest.caseId;

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>ProofVault Verification Certificate</title>
    <style>
      body { font-family: Georgia, "Times New Roman", serif; margin: 0; color: #111111; background: #ffffff; }
      .page { padding: 40px 48px; }
      .header { border-bottom: 4px solid #111111; padding-bottom: 16px; margin-bottom: 24px; }
      .eyebrow { font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase; color: #444444; }
      h1 { margin: 8px 0 4px; font-size: 30px; letter-spacing: 0.06em; text-transform: uppercase; }
      .status { margin-top: 18px; display: inline-block; padding: 8px 14px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; border: 2px solid #111111; }
      .status.pass { background: #e8fff0; }
      .status.fail { background: #fff0f0; }
      .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 24px 0; }
      .card { border: 1px solid #333333; padding: 14px 16px; break-inside: avoid; }
      .card h2 { margin: 0 0 10px; font-size: 13px; letter-spacing: 0.12em; text-transform: uppercase; }
      p, li { font-size: 13px; line-height: 1.5; }
      ul { margin: 8px 0 0 18px; padding: 0; }
      .mono { font-family: "Courier New", monospace; word-break: break-all; }
      .muted { color: #555555; }
      .footer { margin-top: 28px; border-top: 1px solid #cccccc; padding-top: 14px; font-size: 11px; color: #555555; }
      @media print {
        .page { padding: 28px 32px; }
      }
    </style>
  </head>
  <body>
    <main class="page">
      <section class="header">
        <div class="eyebrow">ProofVault Certificate of Integrity</div>
        <h1>${passed ? "Integrity Verified" : "Integrity Review Required"}</h1>
        <p>This certificate is a human-readable wrapper around the machine verification report generated by ProofVault.</p>
        <div class="status ${passed ? "pass" : "fail"}">${passed ? "Pass" : "Findings Present"}</div>
      </section>

      <section class="grid">
        <div class="card">
          <h2>Case Summary</h2>
          <p><strong>Case:</strong> ${escapeHtml(title)}</p>
          <p><strong>Case ID:</strong> ${escapeHtml(report.manifest.caseId)}</p>
          <p><strong>Exported:</strong> ${escapeHtml(formatDisplayDateTime(report.manifest.exportedAt))}</p>
          <p><strong>Checked:</strong> ${escapeHtml(formatDisplayDateTime(report.generatedAt))}</p>
          <p><strong>Source:</strong> ${escapeHtml(report.verificationSource)}</p>
        </div>
        <div class="card">
          <h2>Outcome</h2>
          <p><strong>Verified records:</strong> ${report.verification.verified}</p>
          <p><strong>Mismatched records:</strong> ${report.verification.mismatched}</p>
          <p><strong>Missing records:</strong> ${report.verification.missing}</p>
          <p><strong>Archive seal:</strong> ${report.verification.manifestSealValid ? "Valid" : "Invalid"}</p>
        </div>
      </section>

      <section class="grid">
        <div class="card">
          <h2>Manifest Anchor</h2>
          <p><strong>Format:</strong> ${escapeHtml(report.manifest.outputFormat)}</p>
          <p><strong>Record count:</strong> ${report.manifest.recordCount}</p>
          <p class="mono"><strong>Manifest seal:</strong> ${escapeHtml(report.manifest.integritySeal)}</p>
        </div>
        <div class="card">
          <h2>Snapshot Anchor</h2>
          <p><strong>Evidence checked:</strong> ${report.sourceSnapshot.evidenceItemsChecked}</p>
          <p><strong>Backup exported:</strong> ${escapeHtml(report.sourceSnapshot.backupExportedAt ? formatDisplayDateTime(report.sourceSnapshot.backupExportedAt) : "Not applicable")}</p>
          <p class="mono"><strong>Backup fingerprint:</strong> ${escapeHtml(report.sourceSnapshot.backupSnapshotSha256 ?? "Not applicable")}</p>
        </div>
      </section>

      <section class="card">
        <h2>Manifest Findings</h2>
        ${renderIssueList(report.verification.issues)}
      </section>

      ${renderPolicySection(report)}
      ${renderSecurityFingerprintSection(report)}

      <section class="card" style="margin-top: 20px;">
        <h2>Record Findings</h2>
        ${report.verification.records.length === 0
          ? "<p class=\"muted\">No record-level results available.</p>"
          : report.verification.records
              .filter((record) => record.issues.length > 0)
              .slice(0, 8)
              .map(
                (record) => `<div style="margin-bottom: 12px;"><p><strong>${escapeHtml(record.sourceId)}</strong> (${escapeHtml(record.status)})</p>${renderIssueList(record.issues)}</div>`
              )
              .join("") || "<p class=\"muted\">No record-level issues detected.</p>"}
      </section>

      <section class="footer">
        <p class="mono"><strong>Report SHA-256:</strong> ${escapeHtml(report.reportSha256)}</p>
        <p>This document is intended for printing or PDF export. The underlying JSON verification report remains the authoritative machine-readable record.</p>
      </section>
    </main>
  </body>
</html>`;
}

export function printClinicalVerificationCertificate(report: VerificationReport): void {
  const printWindow = globalThis.open("", "_blank", "noopener,noreferrer,width=960,height=720");

  if (!printWindow) {
    throw new Error("Unable to open a print window on this device.");
  }

  const html = generateClinicalVerificationCertificateHtml(report);

  printWindow.document.open();
  printWindow.document.documentElement.innerHTML = html;
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}