import type { EvidenceItem, LedgerEntry } from "../../../domain/types";
import type { EvidenceDetailView } from "../../../features/evidence/evidenceDetailView";
import { formatSize } from "./formatting";

type EvidenceProvenanceCertificateProps = {
  evidence: EvidenceItem;
  attachment?: EvidenceDetailView["attachment"];
  ledgerEntry: LedgerEntry | null;
  certificateImageUrl: string | null;
  derivativeHash: string | null;
  derivativePreparedAt: string | null;
  isRedactedDerivative: boolean;
};

export function EvidenceProvenanceCertificate({
  evidence,
  attachment,
  ledgerEntry,
  certificateImageUrl,
  derivativeHash,
  derivativePreparedAt,
  isRedactedDerivative,
}: Readonly<EvidenceProvenanceCertificateProps>) {
  return (
    <section className="hidden bg-white p-6 font-mono text-sm text-black [print-color-adjust:exact] [-webkit-print-color-adjust:exact] print:block print:p-8">
      <div className="mb-6 border-b-2 border-black pb-4 print:break-inside-avoid">
        <h1 className="text-2xl font-bold uppercase tracking-widest">Evidence Provenance Certificate</h1>
        <p>Generated by ProofVault | Cryptographic Integrity Log</p>
      </div>

      {isRedactedDerivative ? (
        <div className="mb-6 border-2 border-black bg-gray-200 px-3 py-2 font-bold tracking-wide print:break-inside-avoid">
          REDACTED DERIVATIVE COPY
        </div>
      ) : null}

      <div className="mb-8 grid grid-cols-2 gap-8">
        <div className="print:break-inside-avoid">
          <h2 className="mb-2 border-b border-gray-300 font-bold">Artifact Details</h2>
          <p>
            <strong>File Name:</strong> {attachment?.originalFilename ?? evidence.originalFilename ?? "-"}
          </p>
          <p>
            <strong>MIME Type:</strong> {attachment?.mimeType ?? evidence.mimeType ?? "-"}
          </p>
          <p>
            <strong>Size:</strong> {attachment ? `${formatSize(attachment.sizeBytes)} (${attachment.sizeBytes} bytes)` : "-"}
          </p>
          <p>
            <strong>Recorded At:</strong> {new Date(evidence.recordedAt).toUTCString()}
          </p>
        </div>

        <div className="print:break-inside-avoid">
          <h2 className="mb-2 border-b border-gray-300 font-bold">Cryptographic Fingerprint</h2>
          <p>
            <strong>Algorithm:</strong> SHA-256
          </p>
          {isRedactedDerivative ? (
            <>
              <p className="break-all break-words">
                <strong>Original SHA-256:</strong> {evidence.sha256 ?? "-"}
              </p>
              <p className="break-all break-words">
                <strong>Derivative SHA-256:</strong> {derivativeHash ?? "Preparing..."}
              </p>
              <p>
                <strong>Derivative Prepared:</strong> {derivativePreparedAt ? new Date(derivativePreparedAt).toUTCString() : "-"}
              </p>
            </>
          ) : (
            <p className="break-all break-words">
              <strong>Digest:</strong> {evidence.sha256 ?? "-"}
            </p>
          )}
        </div>
      </div>

      {certificateImageUrl ? (
        <div className="mb-8 print:break-inside-avoid">
          <h2 className="mb-2 border-b border-gray-300 font-bold">
            {isRedactedDerivative ? "Flattened Redacted Artifact" : "Artifact Preview"}
          </h2>
          <img src={certificateImageUrl} alt="Certificate artifact" className="max-h-[480px] w-auto border border-gray-400 object-contain" />
        </div>
      ) : null}

      <div className="mb-8 print:break-inside-avoid">
        <h2 className="mb-2 border-b border-gray-300 font-bold">Chain of Custody (Ledger Anchor)</h2>
        <p>
          <strong>Ledger Entry ID:</strong> {ledgerEntry?.id ?? "Pending"}
        </p>
        <p>
          <strong>Event Type:</strong> {ledgerEntry?.event ?? "Pending"}
        </p>
        <p className="break-all break-words">
          <strong>Chain Hash:</strong> {ledgerEntry?.hash ?? "N/A"}
        </p>
      </div>

      <div className="mt-12 border-t border-gray-300 pt-4 text-center text-xs text-gray-500">
        <p>This certificate proves the existence and integrity of the attached file at the specified time.</p>
        <p>Any modification to the original file will result in a mismatch of the SHA-256 digest.</p>
      </div>
    </section>
  );
}